# Generated by Django 5.1.1 on 2024-09-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
